### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by saladism**
Hi
I am a Paediatrician learning to code.
This is the first time opening a pull request with some format changes and fixing a bug with a default argument.
I hope I have not messed up anything.
Satya.

### CODE REVIEW

**Comment by pacharanero** [comment]
Thanks @saladism! Great first PR and on first scan through it looks great.
I will check through it over the weekend hopefully with @eatyourpeas (who wrote this bit of code) and will probably merge it then

**Comment by saladism** [comment]
[Pycharm](https://www.jetbrains.com/pycharm/), the IDE I am using shows lot of [PEP 8](https://www.python.org/dev/peps/pep-0008/) errors related to length of strings, particularly in comments.
I am happy to clean up the style, as that might help code review, as long as it is not going to add more work to you.

**Comment by pacharanero** [comment]
I think for now we're not being too pernickety on PEP8 for things like line length etc
Over time I'm happy to review and improve whole codebase for this stuff
But right now I'd prefer to focus on functional changes or bug-fix PRs.
Those PRs could include formatting tweaks opportunistically, ie in those same files.
BTW We are using VSCode with the 'Python pack' and using Prettier linter primarily

**Comment by eatyourpeas** [comment]
Before we go any further with these - first of all thank @saladism these are really helpful changes. It does remind me though that alpha is significantly behind unstable and infact all these changes should be in the python package (RCPCHGrowth-python repository) as we extracted this out a couple of months ago into its own repository and published it on pypi. The up to date server now imports this as a dependency

i do remember that @chvanlennep actually picked up the centile band errors already and I have a feeling that is fixed. The constants pick up is new. 

So....
I know it is a pain but @saladism would you be happy to fork the rcpchgrowth-python repo and transfer your changes and make a further pull request?

**Pull request closed without merging**
