### PR TITLE
Rcpch-private/32-normalise-the-script-naming-across-dgc-and-e12

### PR DESCRIPTION
**Pull request by pacharanero**

### CODE REVIEW

**Comment by eatyourpeas** [comment]
before approving this @pacharanero can you confirm this won't break the start script on Azure?

**Comment by pacharanero** [comment]
I've checked and the startup command for production is totally different:

`gunicorn --worker-tmp-dir /dev/shm rcpch-audit-engine.wsgi`

**Comment by eatyourpeas** [comment]
I am getting an error:
```2023-02-07 20:02:02 /bin/sh: 1: [: uvicorn: unexpected operator```
I am wondering if the line is not missing commas?:
```CMD [ "uvicorn" "main:app" "--reload" ]```

**Comment by pacharanero** [comment]
Is this an error running locally? That syntax you're seeing is Dockerfile syntax. The Dockerfile is only used for local development.
So it shouldn't affect the deployment, BUT of course I will want to investigate why you are getting a local error

**Comment by eatyourpeas** [comment]
Perhaps I am doing it wrong. Until now I have been running the server locally with ```s/run-development-server```.
Using your PR I have tried ```s/docker-rebuild``` on first use, and assumed it would be ```s/docker-start``` if ever needed.
I cannot get that to work locally though and the error I get is the one I posted.

**Pull request closed without merging**
