### PR TITLE
add turner reference data as json, add decimal ages to constants.py

### PR DESCRIPTION
**Pull request by eatyourpeas**

### CODE REVIEW

**Comment by pacharanero** [comment]
nice! 

progress.

I wonder if our LMS JSON implementation might need some data to describe the interval between the LMS entries in the future. In the standard growth charts the data is at 2-weekly intervals, but these Turner's charts (I'm guessing) are at 1 year intervals (based on that there are 20 ish of them, and the means roughly look right for the ages)

Should we have 
D (decimal age), L, M, S as the keys in the RCPCH Standard Reference Notation?

@statist7 if we were going to develop a standard notation that could handle a wide range of different LMS tables (with different spaces between references) what else would we need? Would we need a 'header' where we could put a kind of 'capability statement' (eg in Turner's syndrome - only female references here)

**Comment by eatyourpeas** [comment]
I have actually already done this for UK WHO  JSON files. If you look in
the data tables folder there are JSON files with this extra info. We
absolutely could do this. I would like to get rid of the decimal age arrays
and work exclusively from the references.

**Comment by statist7** [comment]
I agree that a slot for metadata would be a good idea, which could be quite general, including the provenance of the data. But I don't see the need to document the structure of the ages in the table, as they document themselves. 

And I agree that the ages should be incorporated within the references. 

I've never been clear how to handle sex, by having either two separate tables or else combining them in one table including a sex indicator variable.

**Comment by pacharanero** [comment]
> I agree that a slot for metadata would be a good idea, which could be quite general, including the provenance of the data. But I don't see the need to document the structure of the ages in the table, as they document themselves.

I agree, metadata within the references themselves might will obviate the need for the separate References listing - we would just have self-internally-documenting-references, and we could pull that data out for a static site generator if we needed a nice looking listing somewhere.

> And I agree that the ages should be incorporated within the references.

Cool. Let's do it

>And I agree that the ages should be incorporated within the references.

It's tricky - one could argue that having single-sex tables is a good solution and it certainly fits with the conditions only ever affecting one sex eg Turner's/Klinefelters. But on the other hand there is something nice about keeping the entire job lot in a single file. Makes it so much easier to import and handle. On balance, I'm in favour of one file and have keys `male` and `female`.

**Comment by BB-1313** [comment]
Hi! Here goes.....Simon has given me a bit of a tour and although I'm still getting my head around GitHub......

> It's tricky - one could argue that having single-sex tables is a good solution and it certainly fits with the conditions only ever affecting one sex eg Turner's/Klinefelters. But on the other hand there is something nice about keeping the entire job lot in a single file. Makes it so much easier to import and handle. On balance, I'm in favour of one file and have keys male and female.

Naive question perhaps?? But is it not computationally more efficient to have separate tables for each type of patient?  Although that may not matter on a single patient basis it might do at scale and even if not would it not be more elegant!
Thinking towards future changes/updates would it not also be easier to replace reference data if it is not a single file and if additional categories of patient appear later on?  What is the intention for the Trisomy 21 ref data?

**Comment by pacharanero** [comment]
> But is it not computationally more efficient to have separate tables for each type of patient?

I personally doubt it, but would of course yield to some benchmarking tests. JSON lookups in memory are preeeety fast.

> would it not be more elegant!

For me, single file with *everything* you are ever going to need for that kind of reference is the more elegant. But again, opinions may vary.

>easier to replace reference data if it is not a single file

In practice we are unlikely to be going into a file to 'replace' bits of it as an 'update. I think far more likely we would be presented with a brand new dataset based on new population research, which we would then JSONify.

**Comment by pacharanero** [comment]
> What is the intention for the Trisomy 21 ref data?

To make an endpoint like `api.rcpch.ac.uk/growth/v1/trisomy21/calculation` that returns accurate centiles for T21 patients.

**Comment by eatyourpeas** [comment]
The difficulty with bundling the decimal ages in with the LMS data is that actual LMS for each measurement and sex is several layers down in the JSON object. This makes it very difficult to iterate when searching for each reference age above and below the requested age. That is why the ages have been moved into the constants file as a simple array. It means the index of the look up age will correspond to the index of a given LMS.
Currently the structure of the reference is:
```
{
    "acknowledgement_text": "UK 1990 reference data, reanalysed 2009.",
    "notes": "",
    "filename": "uk_who_0_20_preterm",
    "measurement": {
        "height": {
            "male": [
                {"L":"","M":"","S":""}, 
                {"L":"","M":"","S":""},
            ],
            "female":[
                 {"L":"","M":"","S":""}, ...
            ]
         },
         "weight": {
               .....
          },......
}
```
As you can see the ages are missing from this. I will put the ages back in and try iterating through the data, instead of an independent array.

**Comment by pacharanero** [comment]
I've got good availability Thurs/Fri if you want to pair on this @eatyourpeas ?

**Pull request merged**
